# This workflow is triggered when a pull request is opened in the TAPM project.
# It adds a label to the pull request and leaves a comment to thank the contributor.
# It also auto-assigns the issue to a specific user.

name: Welcome to the TAPM project pull request

on:
  pull_request_target:
    types: [opened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  asses-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Add Label and thanks comment to Pull request
        uses: actions/github-script@v6
        with:
          script: |
            const issueAuthor = context.payload.sender.login
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs-review']
            })
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
                body: `👋 Thanks for your contribution, @${ issueAuthor }! We appreciate your effort and will review the pull request as soon as possible.`
            })
      - name: Auto-assign issue
        uses: pozil/auto-assign-issue@v2
        with:
          repo-token:  ${{ secrets.GITHUB_TOKEN }}
          assignees: piklumallick